tree: BestLongTracks/TrackTuple

luminosities:
  1p5e32:
    channels:
      ks_to_pipi:
        input: input/minbias_1p5e32_1000evts.root
        modes:
          cheated:
            max_events: 1000
          full:
            max_events: 0
          dist:
            max_events: 200
      bs_to_mumu:
        input: input/bs2mumu_full.root
        modes:
          cheated:
            max_events: 1000
          full:
            max_events: 0
          full_notime:
            max_events: 1000
          dist:
            max_events: 200
      track_pv_association:
        input: input/minbias_1p5e32_1000evts.root
        max_events: 200
