output_dir: public/prod

tree: BestLongTracks/TrackTuple

luminosities:
  1p5e34:
    channels:
      ks_to_pipi:
        input: input/ntuple_minbias_1p5e34_1000evts.root
        modes:
          cheated:
            max_events: 0
          full:
            max_events: 0
          dist:
            max_events: 0
      bs_to_mumu:
        input: input/ntuple_bsmumu_1p5e34_full.root
        modes:
          cheated:
            max_events: 0
          full:
            max_events: 0
          full_notime:
            max_events: 0
          dist:
            max_events: 0
      track_pv_association:
        input: input/ntuple_minbias_1p5e34_1000evts.root
        max_events: 0
      two_track_mva:
        input: input/ntuple_bsmumu_1p5e34_full.root
        max_events: 0
      bs_to_mumu_pvtag:
        input: input/ntuple_bsmumu_1p5e34_full.root
        max_events: 0

  1p3e34:
    channels:
      ks_to_pipi:
        input: input/ntuple_minbias_1p3e34_1000evts.root
        modes:
          cheated:
            max_events: 0
          full:
            max_events: 0
          dist:
            max_events: 0
      bs_to_mumu:
        input: input/ntuple_bsmumu_1p3e34_full.root
        modes:
          cheated:
            max_events: 0
          full:
            max_events: 0
          full_notime:
            max_events: 0
          dist:
            max_events: 0
      track_pv_association:
        input: input/ntuple_minbias_1p3e34_1000evts.root
        max_events: 0
      two_track_mva:
        input: input/ntuple_bsmumu_1p3e34_full.root
        max_events: 0
      bs_to_mumu_pvtag:
        input: input/ntuple_bsmumu_1p3e34_full.root
        max_events: 0

  1p0e34:
    channels:
      ks_to_pipi:
        input: input/ntuple_minbias_1p0e34_1000evts.root
        modes:
          cheated:
            max_events: 0
          full:
            max_events: 0
          dist:
            max_events: 0
      bs_to_mumu:
        input: input/ntuple_bsmumu_1p0e34_full.root
        modes:
          cheated:
            max_events: 0
          full:
            max_events: 0
          full_notime:
            max_events: 0
          dist:
            max_events: 0
      track_pv_association:
        input: input/ntuple_minbias_1p0e34_1000evts.root
        max_events: 0
      two_track_mva:
        input: input/ntuple_bsmumu_1p0e34_full.root
        max_events: 0
      bs_to_mumu_pvtag:
        input: input/ntuple_bsmumu_1p0e34_full.root
        max_events: 0

  run3:
    channels:
      ks_to_pipi:
        input: input/ntuple_minbias_run3_1000evts.root
        modes:
          cheated:
            max_events: 0
          full:
            max_events: 0
          dist:
            max_events: 0
      bs_to_mumu:
        input: input/ntuple_bsmumu_run3_full.root
        modes:
          cheated:
            max_events: 0
          full:
            max_events: 0
          full_notime:
            max_events: 0
          dist:
            max_events: 0
      track_pv_association:
        input: input/ntuple_minbias_run3_1000evts.root
        max_events: 0
      two_track_mva:
        input: input/ntuple_bsmumu_run3_full.root
        max_events: 0
      bs_to_mumu_pvtag:
        input: input/ntuple_bsmumu_run3_full.root
        max_events: 0
